# Generated by Django 4.0.4 on 2022-05-16 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente_Nombre', models.CharField(max_length=20)),
                ('Cliente_Email', models.CharField(max_length=20)),
                ('Cliente_Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo_Marca', models.CharField(max_length=20)),
                ('Equipo_Modelo', models.CharField(max_length=20)),
                ('Equipo_SN', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soporte_Problema', models.CharField(max_length=30)),
                ('Soporte_Comentarios', models.CharField(max_length=30)),
                ('Soporte_Inicio', models.TimeField()),
                ('Soporte_Final', models.TimeField()),
                ('Soporte_Solucionado', models.BooleanField(default=True)),
                ('Soporte_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
                ('Soporte_Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.equipo')),
                ('Soporte_Tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
