# Generated by Django 4.0.4 on 2022-05-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_store_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='Soporte_Final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='Soporte_Inicio',
            field=models.DateField(null=True),
        ),
    ]
