# Generated by Django 4.0.4 on 2022-05-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_soporte_soporte_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='Soporte_Comentarios_Cierre',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
