# Generated by Django 4.0.4 on 2022-05-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_soporte_soporte_comentarios_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='Soporte_Cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
